### ISSUE TITLE
Implement Sleep Tracking CRUD

### ISSUE THREAD

**Issue by da20shadow** [da20shadow/33in1-laravel-rest-api#12]
**Sleep Log Table:**

- [x] ID: A unique identifier for each record in this table.
- [x] User ID: A foreign key that references the ID of the user from the Users table.
- [x] Date: The date when the sleep took place.
- [x] Sleep Start Time: The time when the user went to sleep.
- [x] Sleep End Time: The time when the user woke up.
- [x] Nap Start Time: The time when the user took a nap, if any.
- [x] Nap End Time: The time when the nap ended, if any.
